# dcreator 2.0 - Parallel Volterra dislocation inserter
# Copyright (C) 2000-2026 Erik Bitzek
# SPDX-License-Identifier: GPL-3.0-or-later
# See LICENSE and COPYING.HEADER for full license text and citation info.
"""DislocationSpec — structured representation of a dcreator parameter file.

Serializes to and from the plain-text ``.dissparam`` format understood
by the dcreator CLI. All vectors are stored as length-3 tuples of floats
so they round-trip cleanly through JSON or YAML if a pyiron job needs it.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Iterable, Sequence, Tuple

Vec3 = Tuple[float, float, float]


def _as_vec3(v) -> Vec3:
    t = tuple(float(x) for x in v)
    if len(t) != 3:
        raise ValueError(f"expected length-3 vector, got {v!r}")
    return t  # type: ignore[return-value]


class DisplacementMode(str, Enum):
    UPPER_HALF = "upper_half"
    LOWER_HALF = "lower_half"
    SYMMETRIC  = "symmetric"


class RigidSide(str, Enum):
    RIGHT = "right"
    LEFT  = "left"


class InputFormat(str, Enum):
    AUTO        = "auto"
    LAMMPS_DATA = "lammps_data"
    LAMMPS_DUMP = "lammps_dump"
    IMD         = "imd"


class OutputFormat(str, Enum):
    LAMMPS_DATA = "lammps_data"
    IMD         = "imd"


class LammpsAtomStyle(str, Enum):
    ATOMIC    = "atomic"
    CHARGE    = "charge"
    MOLECULAR = "molecular"
    FULL      = "full"
    BOND      = "bond"


@dataclass
class DislocationSpec:
    """Parameters describing a single Volterra dislocation to insert.

    Sample orientation: supply at least two of ``new_x``, ``new_y``,
    ``new_z``. The third axis is reconstructed by cross product.

    ``burgers`` carries the full Burgers vector (magnitude and direction);
    ``line`` and ``glide_plane_normal`` need only be direction-only.
    """

    # Sample orientation (any two non-zero)
    new_x: Vec3 = (0.0, 0.0, 0.0)
    new_y: Vec3 = (0.0, 0.0, 0.0)
    new_z: Vec3 = (0.0, 0.0, 0.0)

    # Dislocation
    burgers: Vec3 = (0.0, 0.0, 0.0)
    line:    Vec3 = (0.0, 0.0, 0.0)
    glide_plane_normal: Vec3 = (0.0, 0.0, 0.0)
    origin:  Vec3 = (0.0, 0.0, 0.0)
    stripe:  float = 10.0

    # Behavior knobs
    mode:        DisplacementMode = DisplacementMode.UPPER_HALF
    rigid_side:  RigidSide        = RigidSide.RIGHT

    # IO
    input_format:     InputFormat    = InputFormat.AUTO
    output_format:    OutputFormat   = OutputFormat.LAMMPS_DATA
    lammps_atom_style: LammpsAtomStyle = LammpsAtomStyle.ATOMIC

    # Runtime
    num_threads: int = 0

    # --- serialization ---

    def __post_init__(self) -> None:
        # Coerce plain tuples/lists/numpy arrays to strict Vec3
        self.new_x = _as_vec3(self.new_x)
        self.new_y = _as_vec3(self.new_y)
        self.new_z = _as_vec3(self.new_z)
        self.burgers = _as_vec3(self.burgers)
        self.line    = _as_vec3(self.line)
        self.glide_plane_normal = _as_vec3(self.glide_plane_normal)
        self.origin  = _as_vec3(self.origin)
        if isinstance(self.mode, str):
            self.mode = DisplacementMode(self.mode)
        if isinstance(self.rigid_side, str):
            self.rigid_side = RigidSide(self.rigid_side)
        if isinstance(self.input_format, str):
            self.input_format = InputFormat(self.input_format)
        if isinstance(self.output_format, str):
            self.output_format = OutputFormat(self.output_format)
        if isinstance(self.lammps_atom_style, str):
            self.lammps_atom_style = LammpsAtomStyle(self.lammps_atom_style)

    def validate(self) -> None:
        def nonzero(v: Vec3) -> bool:
            return any(abs(x) > 0 for x in v)
        if sum(nonzero(v) for v in (self.new_x, self.new_y, self.new_z)) < 2:
            raise ValueError("need at least two of new_x/new_y/new_z non-zero")
        if not nonzero(self.burgers):
            raise ValueError("burgers is zero")
        if not nonzero(self.line):
            raise ValueError("line is zero")
        if not nonzero(self.glide_plane_normal):
            raise ValueError("glide_plane_normal is zero")
        if self.stripe < 0:
            raise ValueError("stripe must be >= 0")

    def to_dissparam(self, input_file: str, output_file: str) -> str:
        """Return the parameter-file text for the given I/O paths."""
        self.validate()
        lines = [
            f"# dcreator parameter file, generated by pydcreator {input_file!r}",
            f"configfile        {input_file}",
            f"outfile           {output_file}",
            "",
            "# Sample orientation",
            f"new_x             {self.new_x[0]:.17g} {self.new_x[1]:.17g} {self.new_x[2]:.17g}",
            f"new_y             {self.new_y[0]:.17g} {self.new_y[1]:.17g} {self.new_y[2]:.17g}",
            f"new_z             {self.new_z[0]:.17g} {self.new_z[1]:.17g} {self.new_z[2]:.17g}",
            "",
            "# Dislocation",
            f"burgersv          {self.burgers[0]:.17g} {self.burgers[1]:.17g} {self.burgers[2]:.17g}",
            f"linev             {self.line[0]:.17g} {self.line[1]:.17g} {self.line[2]:.17g}",
            f"glideplane        {self.glide_plane_normal[0]:.17g} {self.glide_plane_normal[1]:.17g} {self.glide_plane_normal[2]:.17g}",
            f"point             {self.origin[0]:.17g} {self.origin[1]:.17g} {self.origin[2]:.17g}",
            f"stripe            {self.stripe:.17g}",
            "",
            "# Mode",
            f"displacement_mode {self.mode.value}",
            f"rigid_side        {self.rigid_side.value}",
            "",
            "# IO",
            f"input_format      {self.input_format.value}",
            f"output_format     {self.output_format.value}",
            f"lammps_atom_style {self.lammps_atom_style.value}",
        ]
        if self.num_threads > 0:
            lines += [f"num_threads       {self.num_threads}"]
        return "\n".join(lines) + "\n"

    def write(self, path: str | Path, input_file: str, output_file: str) -> Path:
        path = Path(path)
        path.write_text(self.to_dissparam(input_file, output_file))
        return path

    def to_dict(self) -> dict:
        d = asdict(self)
        # Enums -> str
        for k in ("mode", "rigid_side", "input_format", "output_format", "lammps_atom_style"):
            v = d[k]
            if isinstance(v, Enum):
                d[k] = v.value
        return d
